base:
  project: bank_customer_churn
  data_dir: data
  data_fname: Churn_Modelling.csv
  cat_cols:
  - Geography
  num_cols:
  - CreditScore
  - Age
  - Tenure
  - Balance
  - NumOfProducts
  - HasCrCard
  - IsActiveMember
  - EstimatedSalary
  targ_col: Exited
  random_state: 42
  model_dir: .mlem/model

data_split:
  test_size: 0.15

train:
  model_type: randomforest
  params:
    n_estimators: 150
    max_depth: 10

eval:
  perm_imp_model_path: models/perm_imp.joblib
